"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

type User = { id: string; name: string; email: string; currency: string; timezone: string; createdAt: Date | string };
const currencies = [["NGN", "Nigerian naira"], ["USD", "US dollar"], ["GBP", "British pound"], ["EUR", "Euro"], ["CAD", "Canadian dollar"], ["AUD", "Australian dollar"], ["GHS", "Ghanaian cedi"], ["KES", "Kenyan shilling"], ["ZAR", "South African rand"]];
const timezones = ["Africa/Lagos", "Africa/Accra", "Africa/Nairobi", "Africa/Johannesburg", "Europe/London", "Europe/Paris", "America/New_York", "America/Chicago", "America/Los_Angeles", "Asia/Dubai", "Asia/Kolkata", "Asia/Tokyo", "Australia/Sydney", "UTC"];
const inputClass = "mt-2 w-full rounded-xl border border-slate-300 bg-white px-3.5 py-3 text-slate-950 outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100 disabled:opacity-60 dark:border-slate-700 dark:bg-slate-950 dark:text-white dark:focus:ring-emerald-950";

export function SettingsForms({ user }: { user: User }) {
  const router = useRouter();
  const [profile, setProfile] = useState({ name: user.name, email: user.email, currency: user.currency, timezone: user.timezone });
  const [password, setPassword] = useState({ currentPassword: "", newPassword: "", confirmPassword: "" });
  const [profileStatus, setProfileStatus] = useState({ loading: false, error: "", message: "" });
  const [passwordStatus, setPasswordStatus] = useState({ loading: false, error: "", message: "" });

  async function saveProfile(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setProfileStatus({ loading: true, error: "", message: "" });
    try { const response = await fetch("/api/settings/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, credentials: "same-origin", body: JSON.stringify(profile) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setProfileStatus({ loading: false, error: "", message: data.message }); router.refresh(); }
    catch (error) { setProfileStatus({ loading: false, error: error instanceof Error ? error.message : "Unable to update profile.", message: "" }); }
  }

  async function changePassword(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setPasswordStatus({ loading: true, error: "", message: "" });
    try { const response = await fetch("/api/settings/password", { method: "PATCH", headers: { "Content-Type": "application/json" }, credentials: "same-origin", body: JSON.stringify(password) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setPassword({ currentPassword: "", newPassword: "", confirmPassword: "" }); setPasswordStatus({ loading: false, error: "", message: data.message }); }
    catch (error) { setPasswordStatus({ loading: false, error: error instanceof Error ? error.message : "Unable to change password.", message: "" }); }
  }

  return <section>
    <div><p className="text-sm font-black uppercase tracking-[.25em] text-emerald-600">Settings</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Profile and security</h1><p className="mt-2 text-slate-500 dark:text-slate-400">Manage personal display preferences and your password.</p></div>
    <div className="mt-8 grid gap-6 xl:grid-cols-2">
      <section className="rounded-3xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900 sm:p-7"><h2 className="text-xl font-black">Profile</h2><p className="mt-2 text-sm text-slate-500">Email changes are checked for uniqueness on the server.</p><form onSubmit={saveProfile} className="mt-6 space-y-5">{profileStatus.error || profileStatus.message ? <Status error={profileStatus.error} message={profileStatus.message} /> : null}<label htmlFor="settings-name" className="block text-sm font-bold">Full name<input id="settings-name" autoComplete="name" required minLength={2} maxLength={100} value={profile.name} onChange={(event) => setProfile({ ...profile, name: event.target.value })} className={inputClass} /></label><label htmlFor="settings-email" className="block text-sm font-bold">Email address<input id="settings-email" type="email" autoComplete="email" required maxLength={255} value={profile.email} onChange={(event) => setProfile({ ...profile, email: event.target.value })} className={inputClass} /></label><div className="grid gap-5 sm:grid-cols-2"><label htmlFor="settings-currency" className="block text-sm font-bold">Currency<select id="settings-currency" value={profile.currency} onChange={(event) => setProfile({ ...profile, currency: event.target.value })} className={inputClass}>{currencies.map(([code, name]) => <option key={code} value={code}>{code} — {name}</option>)}</select></label><label htmlFor="settings-timezone" className="block text-sm font-bold">Timezone<select id="settings-timezone" value={profile.timezone} onChange={(event) => setProfile({ ...profile, timezone: event.target.value })} className={inputClass}>{!timezones.includes(profile.timezone) && <option value={profile.timezone}>{profile.timezone}</option>}{timezones.map((timezone) => <option key={timezone} value={timezone}>{timezone.replaceAll("_", " ")}</option>)}</select></label></div><button type="submit" disabled={profileStatus.loading} className="rounded-xl bg-emerald-500 px-5 py-3 font-bold text-slate-950 hover:bg-emerald-400 disabled:opacity-60">{profileStatus.loading ? "Saving..." : "Save profile"}</button></form></section>
      <section className="rounded-3xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900 sm:p-7"><h2 className="text-xl font-black">Change password</h2><p className="mt-2 text-sm text-slate-500">For safety, changing your password revokes every other active session.</p><form onSubmit={changePassword} className="mt-6 space-y-5">{passwordStatus.error || passwordStatus.message ? <Status error={passwordStatus.error} message={passwordStatus.message} /> : null}<label htmlFor="current-password" className="block text-sm font-bold">Current password<input id="current-password" type="password" autoComplete="current-password" required maxLength={128} value={password.currentPassword} onChange={(event) => setPassword({ ...password, currentPassword: event.target.value })} className={inputClass} /></label><label htmlFor="new-password" className="block text-sm font-bold">New password<input id="new-password" type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={password.newPassword} onChange={(event) => setPassword({ ...password, newPassword: event.target.value })} className={inputClass} /><span className="mt-2 block text-xs font-normal text-slate-500">Use at least 12 characters.</span></label><label htmlFor="confirm-new-password" className="block text-sm font-bold">Confirm new password<input id="confirm-new-password" type="password" autoComplete="new-password" required maxLength={128} value={password.confirmPassword} onChange={(event) => setPassword({ ...password, confirmPassword: event.target.value })} className={inputClass} /></label><button type="submit" disabled={passwordStatus.loading} className="rounded-xl bg-slate-950 px-5 py-3 font-bold text-white hover:bg-slate-800 disabled:opacity-60 dark:bg-emerald-500 dark:text-slate-950">{passwordStatus.loading ? "Changing..." : "Change password"}</button></form></section>
    </div>
    <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900 sm:p-7"><h2 className="text-lg font-black">Account information</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Account ID</dt><dd className="mt-1 break-all font-mono">{user.id}</dd></div><div><dt className="text-slate-500">Member since</dt><dd className="mt-1 font-semibold">{new Intl.DateTimeFormat("en", { dateStyle: "long" }).format(new Date(user.createdAt))}</dd></div></dl></section>
  </section>;
}

function Status({ error, message }: { error: string; message: string }) { return <div role={error ? "alert" : "status"} className={`rounded-xl border px-4 py-3 text-sm ${error ? "border-rose-300 bg-rose-50 text-rose-800 dark:border-rose-900 dark:bg-rose-950 dark:text-rose-200" : "border-emerald-300 bg-emerald-50 text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950 dark:text-emerald-200"}`}>{error || message}</div>; }
